# ./.github/workflows/publish.yml
name: Publish

on:
  push:
    branches: [main]

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
      packages: write         # Required for npm publishing
      actions: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install
        shell: bash
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Publish to NPM Registry
        run: npx nx release -y
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Build the package for publishing github registry
        run: npx nx build ngx-build-seo

      - name: Publish to GitHub Registry
        run: cd ./dist/libs/ngx-build-seo && npm publish --registry=https://npm.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}